export const provinces: { title: string }[] = [
  { title: "Benguela" },
  { title: "Bengo" },
  { title: "Bié" },
  { title: "Cabinda" },
  { title: "Cuanza Norte" },
  { title: "Cuanza Sul" },
  { title: "Cunene" },
  { title: "Huambo" },
  { title: "Huíla" },
  { title: "Icolo e Bengo" },
  { title: "Luanda" },
  { title: "Lunda Norte" },
  { title: "Lunda Sul" },
  { title: "Malanje" },
  { title: "Moxico" },
  { title: "Namibe" },
  { title: "Uíge" },
  { title: "Zaire" },
];
